apiVersion: logstash.k8s.elastic.co/v1
kind: logstash
metadata:
  name: logstash-quickstart
spec:
  version: 8.15.2
  podTemplate:
    spec:
      containers:
      - name: logstash
        resources:
          limits:
            memory: 300Mi
            cpu: 0.3
        env:
        - name: LS_JAVA_OPTS
          value: -Xms150m -Xmx150m
